### ISSUE TITLE
api return error

### ISSUE THREAD

**Issue by zakariadhaimi** [Kafiil/covid-ma#4]
The fs.promises API is experimental
(node:10348) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'localName' of null
    at innerText (D:\node_modules\styleless-innertext\index.js:21:47)
    at countryFromNode (D:\node_modules\covid-ma\index.js:49:5)
    at getAllData (D:\node_modules\covid-ma\index.js:69:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by kafiln** [comment]
Hello,
I fixed this issue in the latest version 1.1.1 , please make sure you're using it and get back to me if the problem still persists.
Cheers

**Comment by kafiln** [comment]
@zakariadhaimi  any feedback on this ? 
Can we close it ?

**Comment by zakariadhaimi** [comment]
Hello ,thank you for response you can close it thank you so much
